FROM ${DOCKERHOST}/broad
MAINTAINER Firehose Development Team, firehose-help@broadinstitute.org 

# of the form add <src> <dest> where <src> is a directory of 
# all the method files required for this image (or a directory
# name of such files) and <dest> should always be /task/
# the contents
ADD CallstatsToMaflite /task/

